version: "3"

services:
  nginx:
    image: "/nginx:1.25.1-alpine"
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro